### ISSUE TITLE
这个策略，频率高不高啊，手续费很头疼，怎么办。

### ISSUE THREAD

**Issue by zhiyangzhao** [thusun/sunquant#1]
这个策略，频率高不高啊，手续费很头疼，怎么办。

**Comment by thusun** [comment]
频率取决于阈值Threshold的大小。手续费，把美股每笔交易控制在3000美元以上（每笔最小交易额=0.5 × InvestTotal × InvestRatio × Threshold × Leverage），费用就在千分之一以下，Threshold设置个百分之1、百分之2，手续费占比就不大了。
